package gitops

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type workerStatePRDraft struct {
	Title      string
	BranchName string
	BodyFile   string
	Files      []string
}

func writeWorkerStatePRDraft(root string, result WorkerReconcileExecutionResult) (workerStatePRDraft, error) {
	action := result.Action
	title := fmt.Sprintf("[worker-state:%s] %s", action.Stage, action.ProjectID)
	branchName := fmt.Sprintf("agent/%s/reconcile-%s-state", action.ProjectID, action.Stage)
	bodyFile := filepath.ToSlash(filepath.Join(
		"clusters",
		action.SourceClusterID,
		"projects",
		action.ProjectID,
		"prs",
		"reconcile-"+action.Stage+"-state-pr.md",
	))
	draft := workerStatePRDraft{
		Title:      title,
		BranchName: branchName,
		BodyFile:   bodyFile,
		Files:      workerStatePRFiles(result),
	}

	body := renderWorkerStatePRDraftMarkdown(result, draft)
	path := filepath.Join(root, filepath.FromSlash(bodyFile))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return workerStatePRDraft{}, fmt.Errorf("create worker state PR draft directory: %w", err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		return workerStatePRDraft{}, fmt.Errorf("write worker state PR draft: %w", err)
	}
	return draft, nil
}

func workerStatePRFiles(result WorkerReconcileExecutionResult) []string {
	action := result.Action
	projectPrefix := filepath.ToSlash(filepath.Join("clusters", action.SourceClusterID, "projects", action.ProjectID))
	clusterPrefix := filepath.ToSlash(filepath.Join("clusters", action.SourceClusterID))

	files := make([]string, 0, 4)
	if result.StateFile != "" {
		files = append(files, filepath.ToSlash(filepath.Join(projectPrefix, result.StateFile)))
	}
	if result.EvidenceFile != "" {
		files = append(files, filepath.ToSlash(filepath.Join(projectPrefix, result.EvidenceFile)))
	}
	if action.Stage == "cdc" {
		files = append(files, filepath.ToSlash(filepath.Join(clusterPrefix, "state/cdc-checkpoint.yaml")))
	}
	if result.LeaseFile != "" {
		files = append(files, filepath.ToSlash(filepath.Join(clusterPrefix, result.LeaseFile)))
	}
	return files
}

func renderWorkerStatePRDraftMarkdown(result WorkerReconcileExecutionResult, draft workerStatePRDraft) string {
	action := result.Action

	var b strings.Builder
	fmt.Fprintf(&b, "# PR Draft: %s\n\n", draft.Title)
	b.WriteString("## Summary\n\n")
	fmt.Fprintf(&b, "- Source cluster: `%s`\n", action.SourceClusterID)
	fmt.Fprintf(&b, "- Project: `%s`\n", action.ProjectID)
	fmt.Fprintf(&b, "- Stage: `%s`\n", action.Stage)
	fmt.Fprintf(&b, "- Status: `%s`\n", result.Status)
	fmt.Fprintf(&b, "- Payload hash: `%s`\n", action.PayloadHash)
	fmt.Fprintf(&b, "- Lease ID: `%s`\n", result.LeaseID)
	fmt.Fprintf(&b, "- Branch: `%s`\n", draft.BranchName)
	b.WriteString("- Generated by: `sqlserver2tidb worker-reconcile --execute-next --state-pr-draft`\n\n")

	b.WriteString("## Files To Review\n\n")
	for _, file := range draft.Files {
		fmt.Fprintf(&b, "- `%s`\n", file)
	}

	b.WriteString("\n## Operator Checklist\n\n")
	b.WriteString("- [ ] Confirm the worker action matches the approved payload hash.\n")
	b.WriteString("- [ ] Confirm state and evidence files only contain migration metadata, not plaintext secrets.\n")
	b.WriteString("- [ ] Confirm the source-cluster lease holder and phase match the executed action.\n")
	if action.Stage == "cdc" {
		b.WriteString("- [ ] Confirm the source-cluster CDC checkpoint is consistent with the project CDC evidence.\n")
	}

	b.WriteString("\n## Suggested GitHub Command\n\n")
	b.WriteString("```bash\n")
	fmt.Fprintf(&b, "gh pr create --base main --head %s --title %s --body-file %s\n",
		draft.BranchName,
		shellQuote(draft.Title),
		draft.BodyFile,
	)
	b.WriteString("```\n")
	return b.String()
}
